configs:
  - name: config1
    cmd: command for run your program
    executable: name of your executable
    extension: .extension
    interval: 4
    path: "~/path1"
  
  - name: config2
    cmd: command for run your program
    executable: name of your executable
    extension: .extension
    interval: 5
    path: "~/path2"
  
  - name: config3
    cmd: command for run your program
    executable: name of your executable
    extension: .extension
    interval: 6
    path: "~/path3"
